# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: github.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='github.proto',
  package='blueintel.badapi.github',
  syntax='proto3',
  serialized_options=_b('Z\010githubpb'),
  serialized_pb=_b('\n\x0cgithub.proto\x12\x17\x62lueintel.badapi.github\"\x0b\n\tRepoEmpty\"\x0c\n\nFilesEmpty\"`\n\x04\x46ile\x12\x11\n\tmatchedOn\x18\x01 \x01(\t\x12\x0c\n\x04\x66ile\x18\x02 \x01(\t\x12\x13\n\x0b\x66ileVersion\x18\x03 \x01(\t\x12\x0f\n\x07matches\x18\x04 \x03(\t\x12\x11\n\ttimestamp\x18\x05 \x01(\t\"\x84\x01\n\x04Repo\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0f\n\x07repoURL\x18\x02 \x01(\t\x12\x0c\n\x04orgs\x18\x03 \x03(\t\x12\x11\n\tfirstSeen\x18\x04 \x01(\t\x12\x10\n\x08lastSeen\x18\x05 \x01(\t\x12,\n\x05\x66iles\x18\x06 \x03(\x0b\x32\x1d.blueintel.badapi.github.File\"L\n\tRepoMatch\x12\x0f\n\x07repoURL\x18\x01 \x01(\t\x12\x0c\n\x04\x66ile\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\t\x12\r\n\x05match\x18\x04 \x01(\t\"A\n\x0f\x41lertViewerInfo\x12\x0b\n\x03Org\x18\x01 \x01(\t\x12\x0e\n\x06UserId\x18\x02 \x01(\x03\x12\x11\n\tTimestamp\x18\x03 \x01(\t\"-\n\nAlertMatch\x12\x0c\n\x04\x46ile\x18\x01 \x01(\t\x12\x11\n\tFragments\x18\x02 \x03(\t\"\x7f\n\x05\x41lert\x12\n\n\x02ID\x18\x01 \x01(\t\x12\x0f\n\x07RepoURL\x18\x03 \x01(\t\x12\x10\n\x08Keywords\x18\x05 \x03(\t\x12\x11\n\tTimestamp\x18\x06 \x01(\t\x12\x34\n\x07Matches\x18\x07 \x03(\x0b\x32#.blueintel.badapi.github.AlertMatch\"\x1f\n\x10ListReposRequest\x12\x0b\n\x03org\x18\x01 \x01(\t\"E\n\x11ListReposResponse\x12\x30\n\x04repo\x18\x01 \x01(\x0b\x32\".blueintel.badapi.github.RepoMatch\"T\n\x11ListAlertsRequest\x12\x0b\n\x03org\x18\x01 \x01(\t\x12\x0e\n\x06viewed\x18\x02 \x01(\x08\x12\x11\n\tstartdate\x18\x03 \x01(\t\x12\x0f\n\x07\x65nddate\x18\x04 \x01(\t\"D\n\x12ListAlertsResponse\x12.\n\x06\x41lerts\x18\x01 \x01(\x0b\x32\x1e.blueintel.badapi.github.Alert2\xe2\x01\n\rGithubService\x12\x66\n\tListRepos\x12).blueintel.badapi.github.ListReposRequest\x1a*.blueintel.badapi.github.ListReposResponse\"\x00\x30\x01\x12i\n\nListAlerts\x12*.blueintel.badapi.github.ListAlertsRequest\x1a+.blueintel.badapi.github.ListAlertsResponse\"\x00\x30\x01\x42\nZ\x08githubpbb\x06proto3')
)




_REPOEMPTY = _descriptor.Descriptor(
  name='RepoEmpty',
  full_name='blueintel.badapi.github.RepoEmpty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=41,
  serialized_end=52,
)


_FILESEMPTY = _descriptor.Descriptor(
  name='FilesEmpty',
  full_name='blueintel.badapi.github.FilesEmpty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=54,
  serialized_end=66,
)


_FILE = _descriptor.Descriptor(
  name='File',
  full_name='blueintel.badapi.github.File',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='matchedOn', full_name='blueintel.badapi.github.File.matchedOn', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='file', full_name='blueintel.badapi.github.File.file', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='fileVersion', full_name='blueintel.badapi.github.File.fileVersion', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='matches', full_name='blueintel.badapi.github.File.matches', index=3,
      number=4, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='blueintel.badapi.github.File.timestamp', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=68,
  serialized_end=164,
)


_REPO = _descriptor.Descriptor(
  name='Repo',
  full_name='blueintel.badapi.github.Repo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='blueintel.badapi.github.Repo.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='repoURL', full_name='blueintel.badapi.github.Repo.repoURL', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='orgs', full_name='blueintel.badapi.github.Repo.orgs', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='firstSeen', full_name='blueintel.badapi.github.Repo.firstSeen', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='lastSeen', full_name='blueintel.badapi.github.Repo.lastSeen', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='files', full_name='blueintel.badapi.github.Repo.files', index=5,
      number=6, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=167,
  serialized_end=299,
)


_REPOMATCH = _descriptor.Descriptor(
  name='RepoMatch',
  full_name='blueintel.badapi.github.RepoMatch',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='repoURL', full_name='blueintel.badapi.github.RepoMatch.repoURL', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='file', full_name='blueintel.badapi.github.RepoMatch.file', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='blueintel.badapi.github.RepoMatch.timestamp', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='match', full_name='blueintel.badapi.github.RepoMatch.match', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=301,
  serialized_end=377,
)


_ALERTVIEWERINFO = _descriptor.Descriptor(
  name='AlertViewerInfo',
  full_name='blueintel.badapi.github.AlertViewerInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Org', full_name='blueintel.badapi.github.AlertViewerInfo.Org', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='UserId', full_name='blueintel.badapi.github.AlertViewerInfo.UserId', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Timestamp', full_name='blueintel.badapi.github.AlertViewerInfo.Timestamp', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=379,
  serialized_end=444,
)


_ALERTMATCH = _descriptor.Descriptor(
  name='AlertMatch',
  full_name='blueintel.badapi.github.AlertMatch',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='File', full_name='blueintel.badapi.github.AlertMatch.File', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Fragments', full_name='blueintel.badapi.github.AlertMatch.Fragments', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=446,
  serialized_end=491,
)


_ALERT = _descriptor.Descriptor(
  name='Alert',
  full_name='blueintel.badapi.github.Alert',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ID', full_name='blueintel.badapi.github.Alert.ID', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='RepoURL', full_name='blueintel.badapi.github.Alert.RepoURL', index=1,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Keywords', full_name='blueintel.badapi.github.Alert.Keywords', index=2,
      number=5, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Timestamp', full_name='blueintel.badapi.github.Alert.Timestamp', index=3,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Matches', full_name='blueintel.badapi.github.Alert.Matches', index=4,
      number=7, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=493,
  serialized_end=620,
)


_LISTREPOSREQUEST = _descriptor.Descriptor(
  name='ListReposRequest',
  full_name='blueintel.badapi.github.ListReposRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='org', full_name='blueintel.badapi.github.ListReposRequest.org', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=622,
  serialized_end=653,
)


_LISTREPOSRESPONSE = _descriptor.Descriptor(
  name='ListReposResponse',
  full_name='blueintel.badapi.github.ListReposResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='repo', full_name='blueintel.badapi.github.ListReposResponse.repo', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=655,
  serialized_end=724,
)


_LISTALERTSREQUEST = _descriptor.Descriptor(
  name='ListAlertsRequest',
  full_name='blueintel.badapi.github.ListAlertsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='org', full_name='blueintel.badapi.github.ListAlertsRequest.org', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='viewed', full_name='blueintel.badapi.github.ListAlertsRequest.viewed', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='startdate', full_name='blueintel.badapi.github.ListAlertsRequest.startdate', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='enddate', full_name='blueintel.badapi.github.ListAlertsRequest.enddate', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=726,
  serialized_end=810,
)


_LISTALERTSRESPONSE = _descriptor.Descriptor(
  name='ListAlertsResponse',
  full_name='blueintel.badapi.github.ListAlertsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Alerts', full_name='blueintel.badapi.github.ListAlertsResponse.Alerts', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=812,
  serialized_end=880,
)

_REPO.fields_by_name['files'].message_type = _FILE
_ALERT.fields_by_name['Matches'].message_type = _ALERTMATCH
_LISTREPOSRESPONSE.fields_by_name['repo'].message_type = _REPOMATCH
_LISTALERTSRESPONSE.fields_by_name['Alerts'].message_type = _ALERT
DESCRIPTOR.message_types_by_name['RepoEmpty'] = _REPOEMPTY
DESCRIPTOR.message_types_by_name['FilesEmpty'] = _FILESEMPTY
DESCRIPTOR.message_types_by_name['File'] = _FILE
DESCRIPTOR.message_types_by_name['Repo'] = _REPO
DESCRIPTOR.message_types_by_name['RepoMatch'] = _REPOMATCH
DESCRIPTOR.message_types_by_name['AlertViewerInfo'] = _ALERTVIEWERINFO
DESCRIPTOR.message_types_by_name['AlertMatch'] = _ALERTMATCH
DESCRIPTOR.message_types_by_name['Alert'] = _ALERT
DESCRIPTOR.message_types_by_name['ListReposRequest'] = _LISTREPOSREQUEST
DESCRIPTOR.message_types_by_name['ListReposResponse'] = _LISTREPOSRESPONSE
DESCRIPTOR.message_types_by_name['ListAlertsRequest'] = _LISTALERTSREQUEST
DESCRIPTOR.message_types_by_name['ListAlertsResponse'] = _LISTALERTSRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RepoEmpty = _reflection.GeneratedProtocolMessageType('RepoEmpty', (_message.Message,), dict(
  DESCRIPTOR = _REPOEMPTY,
  __module__ = 'github_pb2'
  # @@protoc_insertion_point(class_scope:blueintel.badapi.github.RepoEmpty)
  ))
_sym_db.RegisterMessage(RepoEmpty)

FilesEmpty = _reflection.GeneratedProtocolMessageType('FilesEmpty', (_message.Message,), dict(
  DESCRIPTOR = _FILESEMPTY,
  __module__ = 'github_pb2'
  # @@protoc_insertion_point(class_scope:blueintel.badapi.github.FilesEmpty)
  ))
_sym_db.RegisterMessage(FilesEmpty)

File = _reflection.GeneratedProtocolMessageType('File', (_message.Message,), dict(
  DESCRIPTOR = _FILE,
  __module__ = 'github_pb2'
  # @@protoc_insertion_point(class_scope:blueintel.badapi.github.File)
  ))
_sym_db.RegisterMessage(File)

Repo = _reflection.GeneratedProtocolMessageType('Repo', (_message.Message,), dict(
  DESCRIPTOR = _REPO,
  __module__ = 'github_pb2'
  # @@protoc_insertion_point(class_scope:blueintel.badapi.github.Repo)
  ))
_sym_db.RegisterMessage(Repo)

RepoMatch = _reflection.GeneratedProtocolMessageType('RepoMatch', (_message.Message,), dict(
  DESCRIPTOR = _REPOMATCH,
  __module__ = 'github_pb2'
  # @@protoc_insertion_point(class_scope:blueintel.badapi.github.RepoMatch)
  ))
_sym_db.RegisterMessage(RepoMatch)

AlertViewerInfo = _reflection.GeneratedProtocolMessageType('AlertViewerInfo', (_message.Message,), dict(
  DESCRIPTOR = _ALERTVIEWERINFO,
  __module__ = 'github_pb2'
  # @@protoc_insertion_point(class_scope:blueintel.badapi.github.AlertViewerInfo)
  ))
_sym_db.RegisterMessage(AlertViewerInfo)

AlertMatch = _reflection.GeneratedProtocolMessageType('AlertMatch', (_message.Message,), dict(
  DESCRIPTOR = _ALERTMATCH,
  __module__ = 'github_pb2'
  # @@protoc_insertion_point(class_scope:blueintel.badapi.github.AlertMatch)
  ))
_sym_db.RegisterMessage(AlertMatch)

Alert = _reflection.GeneratedProtocolMessageType('Alert', (_message.Message,), dict(
  DESCRIPTOR = _ALERT,
  __module__ = 'github_pb2'
  # @@protoc_insertion_point(class_scope:blueintel.badapi.github.Alert)
  ))
_sym_db.RegisterMessage(Alert)

ListReposRequest = _reflection.GeneratedProtocolMessageType('ListReposRequest', (_message.Message,), dict(
  DESCRIPTOR = _LISTREPOSREQUEST,
  __module__ = 'github_pb2'
  # @@protoc_insertion_point(class_scope:blueintel.badapi.github.ListReposRequest)
  ))
_sym_db.RegisterMessage(ListReposRequest)

ListReposResponse = _reflection.GeneratedProtocolMessageType('ListReposResponse', (_message.Message,), dict(
  DESCRIPTOR = _LISTREPOSRESPONSE,
  __module__ = 'github_pb2'
  # @@protoc_insertion_point(class_scope:blueintel.badapi.github.ListReposResponse)
  ))
_sym_db.RegisterMessage(ListReposResponse)

ListAlertsRequest = _reflection.GeneratedProtocolMessageType('ListAlertsRequest', (_message.Message,), dict(
  DESCRIPTOR = _LISTALERTSREQUEST,
  __module__ = 'github_pb2'
  # @@protoc_insertion_point(class_scope:blueintel.badapi.github.ListAlertsRequest)
  ))
_sym_db.RegisterMessage(ListAlertsRequest)

ListAlertsResponse = _reflection.GeneratedProtocolMessageType('ListAlertsResponse', (_message.Message,), dict(
  DESCRIPTOR = _LISTALERTSRESPONSE,
  __module__ = 'github_pb2'
  # @@protoc_insertion_point(class_scope:blueintel.badapi.github.ListAlertsResponse)
  ))
_sym_db.RegisterMessage(ListAlertsResponse)


DESCRIPTOR._options = None

_GITHUBSERVICE = _descriptor.ServiceDescriptor(
  name='GithubService',
  full_name='blueintel.badapi.github.GithubService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=883,
  serialized_end=1109,
  methods=[
  _descriptor.MethodDescriptor(
    name='ListRepos',
    full_name='blueintel.badapi.github.GithubService.ListRepos',
    index=0,
    containing_service=None,
    input_type=_LISTREPOSREQUEST,
    output_type=_LISTREPOSRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='ListAlerts',
    full_name='blueintel.badapi.github.GithubService.ListAlerts',
    index=1,
    containing_service=None,
    input_type=_LISTALERTSREQUEST,
    output_type=_LISTALERTSRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_GITHUBSERVICE)

DESCRIPTOR.services_by_name['GithubService'] = _GITHUBSERVICE

# @@protoc_insertion_point(module_scope)
