# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: badapigeoip.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x62\x61\x64\x61pigeoip.proto\x12\x1f\x62lueintel.badapi.badaapigeoippb\"\x1e\n\x10ListGeoIPRequest\x12\n\n\x02ip\x18\x01 \x01(\t\"#\n\x15\x42\x61tchListGeoIPRequest\x12\n\n\x02ip\x18\x01 \x03(\t\"\xb8\x01\n\x05GeoIP\x12\n\n\x02ip\x18\x01 \x01(\t\x12\x13\n\x0b\x63ountrycode\x18\x02 \x01(\t\x12\x0f\n\x07\x63ountry\x18\x03 \x01(\t\x12\x0e\n\x06region\x18\x04 \x01(\t\x12\x0c\n\x04\x63ity\x18\x05 \x01(\t\x12\x10\n\x08latitude\x18\x07 \x01(\x02\x12\x11\n\tlongitude\x18\x08 \x01(\x02\x12\x0b\n\x03zip\x18\t \x01(\t\x12\x10\n\x08timezone\x18\n \x01(\t\x12\x0b\n\x03isp\x18\x0b \x01(\t\x12\x0e\n\x06\x64omain\x18\x0c \x01(\t2\xee\x01\n\x0cGeoIPService\x12h\n\tListGeoIP\x12\x31.blueintel.badapi.badaapigeoippb.ListGeoIPRequest\x1a&.blueintel.badapi.badaapigeoippb.GeoIP\"\x00\x12t\n\x0e\x42\x61tchListGeoIP\x12\x36.blueintel.badapi.badaapigeoippb.BatchListGeoIPRequest\x1a&.blueintel.badapi.badaapigeoippb.GeoIP\"\x00\x30\x01\x42\x12Z\x10.;badaapigeoippbb\x06proto3')



_LISTGEOIPREQUEST = DESCRIPTOR.message_types_by_name['ListGeoIPRequest']
_BATCHLISTGEOIPREQUEST = DESCRIPTOR.message_types_by_name['BatchListGeoIPRequest']
_GEOIP = DESCRIPTOR.message_types_by_name['GeoIP']
ListGeoIPRequest = _reflection.GeneratedProtocolMessageType('ListGeoIPRequest', (_message.Message,), {
  'DESCRIPTOR' : _LISTGEOIPREQUEST,
  '__module__' : 'badapigeoip_pb2'
  # @@protoc_insertion_point(class_scope:blueintel.badapi.badaapigeoippb.ListGeoIPRequest)
  })
_sym_db.RegisterMessage(ListGeoIPRequest)

BatchListGeoIPRequest = _reflection.GeneratedProtocolMessageType('BatchListGeoIPRequest', (_message.Message,), {
  'DESCRIPTOR' : _BATCHLISTGEOIPREQUEST,
  '__module__' : 'badapigeoip_pb2'
  # @@protoc_insertion_point(class_scope:blueintel.badapi.badaapigeoippb.BatchListGeoIPRequest)
  })
_sym_db.RegisterMessage(BatchListGeoIPRequest)

GeoIP = _reflection.GeneratedProtocolMessageType('GeoIP', (_message.Message,), {
  'DESCRIPTOR' : _GEOIP,
  '__module__' : 'badapigeoip_pb2'
  # @@protoc_insertion_point(class_scope:blueintel.badapi.badaapigeoippb.GeoIP)
  })
_sym_db.RegisterMessage(GeoIP)

_GEOIPSERVICE = DESCRIPTOR.services_by_name['GeoIPService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\020.;badaapigeoippb'
  _LISTGEOIPREQUEST._serialized_start=54
  _LISTGEOIPREQUEST._serialized_end=84
  _BATCHLISTGEOIPREQUEST._serialized_start=86
  _BATCHLISTGEOIPREQUEST._serialized_end=121
  _GEOIP._serialized_start=124
  _GEOIP._serialized_end=308
  _GEOIPSERVICE._serialized_start=311
  _GEOIPSERVICE._serialized_end=549
# @@protoc_insertion_point(module_scope)
