# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import badapigeoip_pb2 as badapigeoip__pb2


class GeoIPServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListGeoIP = channel.unary_unary(
                '/blueintel.badapi.badaapigeoippb.GeoIPService/ListGeoIP',
                request_serializer=badapigeoip__pb2.ListGeoIPRequest.SerializeToString,
                response_deserializer=badapigeoip__pb2.GeoIP.FromString,
                )
        self.BatchListGeoIP = channel.unary_stream(
                '/blueintel.badapi.badaapigeoippb.GeoIPService/BatchListGeoIP',
                request_serializer=badapigeoip__pb2.BatchListGeoIPRequest.SerializeToString,
                response_deserializer=badapigeoip__pb2.GeoIP.FromString,
                )


class GeoIPServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ListGeoIP(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BatchListGeoIP(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GeoIPServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListGeoIP': grpc.unary_unary_rpc_method_handler(
                    servicer.ListGeoIP,
                    request_deserializer=badapigeoip__pb2.ListGeoIPRequest.FromString,
                    response_serializer=badapigeoip__pb2.GeoIP.SerializeToString,
            ),
            'BatchListGeoIP': grpc.unary_stream_rpc_method_handler(
                    servicer.BatchListGeoIP,
                    request_deserializer=badapigeoip__pb2.BatchListGeoIPRequest.FromString,
                    response_serializer=badapigeoip__pb2.GeoIP.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'blueintel.badapi.badaapigeoippb.GeoIPService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class GeoIPService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListGeoIP(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/blueintel.badapi.badaapigeoippb.GeoIPService/ListGeoIP',
            badapigeoip__pb2.ListGeoIPRequest.SerializeToString,
            badapigeoip__pb2.GeoIP.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def BatchListGeoIP(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/blueintel.badapi.badaapigeoippb.GeoIPService/BatchListGeoIP',
            badapigeoip__pb2.BatchListGeoIPRequest.SerializeToString,
            badapigeoip__pb2.GeoIP.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
