# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: badapigeoip.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='badapigeoip.proto',
  package='blueintel.badapi.badaapigeoippb',
  syntax='proto3',
  serialized_options=b'Z\020.;badaapigeoippb',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x11\x62\x61\x64\x61pigeoip.proto\x12\x1f\x62lueintel.badapi.badaapigeoippb\"\x1e\n\x10ListGeoIPRequest\x12\n\n\x02ip\x18\x01 \x01(\t\"#\n\x15\x42\x61tchListGeoIPRequest\x12\n\n\x02ip\x18\x01 \x03(\t\"\xb8\x01\n\x05GeoIP\x12\n\n\x02ip\x18\x01 \x01(\t\x12\x13\n\x0b\x63ountrycode\x18\x02 \x01(\t\x12\x0f\n\x07\x63ountry\x18\x03 \x01(\t\x12\x0e\n\x06region\x18\x04 \x01(\t\x12\x0c\n\x04\x63ity\x18\x05 \x01(\t\x12\x10\n\x08latitude\x18\x07 \x01(\x02\x12\x11\n\tlongitude\x18\x08 \x01(\x02\x12\x0b\n\x03zip\x18\t \x01(\t\x12\x10\n\x08timezone\x18\n \x01(\t\x12\x0b\n\x03isp\x18\x0b \x01(\t\x12\x0e\n\x06\x64omain\x18\x0c \x01(\t2\xee\x01\n\x0cGeoIPService\x12h\n\tListGeoIP\x12\x31.blueintel.badapi.badaapigeoippb.ListGeoIPRequest\x1a&.blueintel.badapi.badaapigeoippb.GeoIP\"\x00\x12t\n\x0e\x42\x61tchListGeoIP\x12\x36.blueintel.badapi.badaapigeoippb.BatchListGeoIPRequest\x1a&.blueintel.badapi.badaapigeoippb.GeoIP\"\x00\x30\x01\x42\x12Z\x10.;badaapigeoippbb\x06proto3'
)




_LISTGEOIPREQUEST = _descriptor.Descriptor(
  name='ListGeoIPRequest',
  full_name='blueintel.badapi.badaapigeoippb.ListGeoIPRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ip', full_name='blueintel.badapi.badaapigeoippb.ListGeoIPRequest.ip', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=54,
  serialized_end=84,
)


_BATCHLISTGEOIPREQUEST = _descriptor.Descriptor(
  name='BatchListGeoIPRequest',
  full_name='blueintel.badapi.badaapigeoippb.BatchListGeoIPRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ip', full_name='blueintel.badapi.badaapigeoippb.BatchListGeoIPRequest.ip', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=86,
  serialized_end=121,
)


_GEOIP = _descriptor.Descriptor(
  name='GeoIP',
  full_name='blueintel.badapi.badaapigeoippb.GeoIP',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ip', full_name='blueintel.badapi.badaapigeoippb.GeoIP.ip', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='countrycode', full_name='blueintel.badapi.badaapigeoippb.GeoIP.countrycode', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='country', full_name='blueintel.badapi.badaapigeoippb.GeoIP.country', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='region', full_name='blueintel.badapi.badaapigeoippb.GeoIP.region', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='city', full_name='blueintel.badapi.badaapigeoippb.GeoIP.city', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='latitude', full_name='blueintel.badapi.badaapigeoippb.GeoIP.latitude', index=5,
      number=7, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='longitude', full_name='blueintel.badapi.badaapigeoippb.GeoIP.longitude', index=6,
      number=8, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='zip', full_name='blueintel.badapi.badaapigeoippb.GeoIP.zip', index=7,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='timezone', full_name='blueintel.badapi.badaapigeoippb.GeoIP.timezone', index=8,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='isp', full_name='blueintel.badapi.badaapigeoippb.GeoIP.isp', index=9,
      number=11, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='domain', full_name='blueintel.badapi.badaapigeoippb.GeoIP.domain', index=10,
      number=12, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=124,
  serialized_end=308,
)

DESCRIPTOR.message_types_by_name['ListGeoIPRequest'] = _LISTGEOIPREQUEST
DESCRIPTOR.message_types_by_name['BatchListGeoIPRequest'] = _BATCHLISTGEOIPREQUEST
DESCRIPTOR.message_types_by_name['GeoIP'] = _GEOIP
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ListGeoIPRequest = _reflection.GeneratedProtocolMessageType('ListGeoIPRequest', (_message.Message,), {
  'DESCRIPTOR' : _LISTGEOIPREQUEST,
  '__module__' : 'badapigeoip_pb2'
  # @@protoc_insertion_point(class_scope:blueintel.badapi.badaapigeoippb.ListGeoIPRequest)
  })
_sym_db.RegisterMessage(ListGeoIPRequest)

BatchListGeoIPRequest = _reflection.GeneratedProtocolMessageType('BatchListGeoIPRequest', (_message.Message,), {
  'DESCRIPTOR' : _BATCHLISTGEOIPREQUEST,
  '__module__' : 'badapigeoip_pb2'
  # @@protoc_insertion_point(class_scope:blueintel.badapi.badaapigeoippb.BatchListGeoIPRequest)
  })
_sym_db.RegisterMessage(BatchListGeoIPRequest)

GeoIP = _reflection.GeneratedProtocolMessageType('GeoIP', (_message.Message,), {
  'DESCRIPTOR' : _GEOIP,
  '__module__' : 'badapigeoip_pb2'
  # @@protoc_insertion_point(class_scope:blueintel.badapi.badaapigeoippb.GeoIP)
  })
_sym_db.RegisterMessage(GeoIP)


DESCRIPTOR._options = None

_GEOIPSERVICE = _descriptor.ServiceDescriptor(
  name='GeoIPService',
  full_name='blueintel.badapi.badaapigeoippb.GeoIPService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=311,
  serialized_end=549,
  methods=[
  _descriptor.MethodDescriptor(
    name='ListGeoIP',
    full_name='blueintel.badapi.badaapigeoippb.GeoIPService.ListGeoIP',
    index=0,
    containing_service=None,
    input_type=_LISTGEOIPREQUEST,
    output_type=_GEOIP,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='BatchListGeoIP',
    full_name='blueintel.badapi.badaapigeoippb.GeoIPService.BatchListGeoIP',
    index=1,
    containing_service=None,
    input_type=_BATCHLISTGEOIPREQUEST,
    output_type=_GEOIP,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_GEOIPSERVICE)

DESCRIPTOR.services_by_name['GeoIPService'] = _GEOIPSERVICE

# @@protoc_insertion_point(module_scope)
