# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: badpanda.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x62\x61\x64panda.proto\x12\x19\x62lueintel.badapi.badpanda\"\x88\x01\n\x15\x42\x61\x64pandaSearchRequest\x12\x10\n\x08org_name\x18\x01 \x01(\t\x12\x12\n\nstart_date\x18\x02 \x01(\t\x12\x10\n\x08\x65nd_date\x18\x03 \x01(\t\x12\x0f\n\x07sources\x18\x04 \x01(\t\x12\x14\n\x0creason_types\x18\x05 \x01(\t\x12\x10\n\x08max_hits\x18\x06 \x01(\x03\",\n\x16\x42\x61\x64pandaSearchResponse\x12\x12\n\njsonRecord\x18\x01 \x01(\t\"9\n\x15SearchByDomainRequest\x12\x10\n\x08org_name\x18\x01 \x01(\t\x12\x0e\n\x06\x64omain\x18\x02 \x01(\t\"1\n\x11SearchByIPRequest\x12\x10\n\x08org_name\x18\x01 \x01(\t\x12\n\n\x02ip\x18\x02 \x01(\t2\xfb\x02\n\x0f\x42\x61\x64pandaService\x12z\n\x0fSearchBadpandas\x12\x30.blueintel.badapi.badpanda.BadpandaSearchRequest\x1a\x31.blueintel.badapi.badpanda.BadpandaSearchResponse\"\x00\x30\x01\x12y\n\x0eSearchByDomain\x12\x30.blueintel.badapi.badpanda.SearchByDomainRequest\x1a\x31.blueintel.badapi.badpanda.BadpandaSearchResponse\"\x00\x30\x01\x12q\n\nSearchByIP\x12,.blueintel.badapi.badpanda.SearchByIPRequest\x1a\x31.blueintel.badapi.badpanda.BadpandaSearchResponse\"\x00\x30\x01\x42\x0eZ\x0c.;badpandapbb\x06proto3')



_BADPANDASEARCHREQUEST = DESCRIPTOR.message_types_by_name['BadpandaSearchRequest']
_BADPANDASEARCHRESPONSE = DESCRIPTOR.message_types_by_name['BadpandaSearchResponse']
_SEARCHBYDOMAINREQUEST = DESCRIPTOR.message_types_by_name['SearchByDomainRequest']
_SEARCHBYIPREQUEST = DESCRIPTOR.message_types_by_name['SearchByIPRequest']
BadpandaSearchRequest = _reflection.GeneratedProtocolMessageType('BadpandaSearchRequest', (_message.Message,), {
  'DESCRIPTOR' : _BADPANDASEARCHREQUEST,
  '__module__' : 'badpanda_pb2'
  # @@protoc_insertion_point(class_scope:blueintel.badapi.badpanda.BadpandaSearchRequest)
  })
_sym_db.RegisterMessage(BadpandaSearchRequest)

BadpandaSearchResponse = _reflection.GeneratedProtocolMessageType('BadpandaSearchResponse', (_message.Message,), {
  'DESCRIPTOR' : _BADPANDASEARCHRESPONSE,
  '__module__' : 'badpanda_pb2'
  # @@protoc_insertion_point(class_scope:blueintel.badapi.badpanda.BadpandaSearchResponse)
  })
_sym_db.RegisterMessage(BadpandaSearchResponse)

SearchByDomainRequest = _reflection.GeneratedProtocolMessageType('SearchByDomainRequest', (_message.Message,), {
  'DESCRIPTOR' : _SEARCHBYDOMAINREQUEST,
  '__module__' : 'badpanda_pb2'
  # @@protoc_insertion_point(class_scope:blueintel.badapi.badpanda.SearchByDomainRequest)
  })
_sym_db.RegisterMessage(SearchByDomainRequest)

SearchByIPRequest = _reflection.GeneratedProtocolMessageType('SearchByIPRequest', (_message.Message,), {
  'DESCRIPTOR' : _SEARCHBYIPREQUEST,
  '__module__' : 'badpanda_pb2'
  # @@protoc_insertion_point(class_scope:blueintel.badapi.badpanda.SearchByIPRequest)
  })
_sym_db.RegisterMessage(SearchByIPRequest)

_BADPANDASERVICE = DESCRIPTOR.services_by_name['BadpandaService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\014.;badpandapb'
  _BADPANDASEARCHREQUEST._serialized_start=46
  _BADPANDASEARCHREQUEST._serialized_end=182
  _BADPANDASEARCHRESPONSE._serialized_start=184
  _BADPANDASEARCHRESPONSE._serialized_end=228
  _SEARCHBYDOMAINREQUEST._serialized_start=230
  _SEARCHBYDOMAINREQUEST._serialized_end=287
  _SEARCHBYIPREQUEST._serialized_start=289
  _SEARCHBYIPREQUEST._serialized_end=338
  _BADPANDASERVICE._serialized_start=341
  _BADPANDASERVICE._serialized_end=720
# @@protoc_insertion_point(module_scope)
