# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: badpanda.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='badpanda.proto',
  package='blueintel.badapi.badpanda',
  syntax='proto3',
  serialized_options=b'Z\014.;badpandapb',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0e\x62\x61\x64panda.proto\x12\x19\x62lueintel.badapi.badpanda\"\x88\x01\n\x15\x42\x61\x64pandaSearchRequest\x12\x10\n\x08org_name\x18\x01 \x01(\t\x12\x12\n\nstart_date\x18\x02 \x01(\t\x12\x10\n\x08\x65nd_date\x18\x03 \x01(\t\x12\x0f\n\x07sources\x18\x04 \x01(\t\x12\x14\n\x0creason_types\x18\x05 \x01(\t\x12\x10\n\x08max_hits\x18\x06 \x01(\x03\",\n\x16\x42\x61\x64pandaSearchResponse\x12\x12\n\njsonRecord\x18\x01 \x01(\t\"9\n\x15SearchByDomainRequest\x12\x10\n\x08org_name\x18\x01 \x01(\t\x12\x0e\n\x06\x64omain\x18\x02 \x01(\t\"1\n\x11SearchByIPRequest\x12\x10\n\x08org_name\x18\x01 \x01(\t\x12\n\n\x02ip\x18\x02 \x01(\t2\xfb\x02\n\x0f\x42\x61\x64pandaService\x12z\n\x0fSearchBadpandas\x12\x30.blueintel.badapi.badpanda.BadpandaSearchRequest\x1a\x31.blueintel.badapi.badpanda.BadpandaSearchResponse\"\x00\x30\x01\x12y\n\x0eSearchByDomain\x12\x30.blueintel.badapi.badpanda.SearchByDomainRequest\x1a\x31.blueintel.badapi.badpanda.BadpandaSearchResponse\"\x00\x30\x01\x12q\n\nSearchByIP\x12,.blueintel.badapi.badpanda.SearchByIPRequest\x1a\x31.blueintel.badapi.badpanda.BadpandaSearchResponse\"\x00\x30\x01\x42\x0eZ\x0c.;badpandapbb\x06proto3'
)




_BADPANDASEARCHREQUEST = _descriptor.Descriptor(
  name='BadpandaSearchRequest',
  full_name='blueintel.badapi.badpanda.BadpandaSearchRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='org_name', full_name='blueintel.badapi.badpanda.BadpandaSearchRequest.org_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='start_date', full_name='blueintel.badapi.badpanda.BadpandaSearchRequest.start_date', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='end_date', full_name='blueintel.badapi.badpanda.BadpandaSearchRequest.end_date', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sources', full_name='blueintel.badapi.badpanda.BadpandaSearchRequest.sources', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='reason_types', full_name='blueintel.badapi.badpanda.BadpandaSearchRequest.reason_types', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='max_hits', full_name='blueintel.badapi.badpanda.BadpandaSearchRequest.max_hits', index=5,
      number=6, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=46,
  serialized_end=182,
)


_BADPANDASEARCHRESPONSE = _descriptor.Descriptor(
  name='BadpandaSearchResponse',
  full_name='blueintel.badapi.badpanda.BadpandaSearchResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='jsonRecord', full_name='blueintel.badapi.badpanda.BadpandaSearchResponse.jsonRecord', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=184,
  serialized_end=228,
)


_SEARCHBYDOMAINREQUEST = _descriptor.Descriptor(
  name='SearchByDomainRequest',
  full_name='blueintel.badapi.badpanda.SearchByDomainRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='org_name', full_name='blueintel.badapi.badpanda.SearchByDomainRequest.org_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='domain', full_name='blueintel.badapi.badpanda.SearchByDomainRequest.domain', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=230,
  serialized_end=287,
)


_SEARCHBYIPREQUEST = _descriptor.Descriptor(
  name='SearchByIPRequest',
  full_name='blueintel.badapi.badpanda.SearchByIPRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='org_name', full_name='blueintel.badapi.badpanda.SearchByIPRequest.org_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ip', full_name='blueintel.badapi.badpanda.SearchByIPRequest.ip', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=289,
  serialized_end=338,
)

DESCRIPTOR.message_types_by_name['BadpandaSearchRequest'] = _BADPANDASEARCHREQUEST
DESCRIPTOR.message_types_by_name['BadpandaSearchResponse'] = _BADPANDASEARCHRESPONSE
DESCRIPTOR.message_types_by_name['SearchByDomainRequest'] = _SEARCHBYDOMAINREQUEST
DESCRIPTOR.message_types_by_name['SearchByIPRequest'] = _SEARCHBYIPREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

BadpandaSearchRequest = _reflection.GeneratedProtocolMessageType('BadpandaSearchRequest', (_message.Message,), {
  'DESCRIPTOR' : _BADPANDASEARCHREQUEST,
  '__module__' : 'badpanda_pb2'
  # @@protoc_insertion_point(class_scope:blueintel.badapi.badpanda.BadpandaSearchRequest)
  })
_sym_db.RegisterMessage(BadpandaSearchRequest)

BadpandaSearchResponse = _reflection.GeneratedProtocolMessageType('BadpandaSearchResponse', (_message.Message,), {
  'DESCRIPTOR' : _BADPANDASEARCHRESPONSE,
  '__module__' : 'badpanda_pb2'
  # @@protoc_insertion_point(class_scope:blueintel.badapi.badpanda.BadpandaSearchResponse)
  })
_sym_db.RegisterMessage(BadpandaSearchResponse)

SearchByDomainRequest = _reflection.GeneratedProtocolMessageType('SearchByDomainRequest', (_message.Message,), {
  'DESCRIPTOR' : _SEARCHBYDOMAINREQUEST,
  '__module__' : 'badpanda_pb2'
  # @@protoc_insertion_point(class_scope:blueintel.badapi.badpanda.SearchByDomainRequest)
  })
_sym_db.RegisterMessage(SearchByDomainRequest)

SearchByIPRequest = _reflection.GeneratedProtocolMessageType('SearchByIPRequest', (_message.Message,), {
  'DESCRIPTOR' : _SEARCHBYIPREQUEST,
  '__module__' : 'badpanda_pb2'
  # @@protoc_insertion_point(class_scope:blueintel.badapi.badpanda.SearchByIPRequest)
  })
_sym_db.RegisterMessage(SearchByIPRequest)


DESCRIPTOR._options = None

_BADPANDASERVICE = _descriptor.ServiceDescriptor(
  name='BadpandaService',
  full_name='blueintel.badapi.badpanda.BadpandaService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=341,
  serialized_end=720,
  methods=[
  _descriptor.MethodDescriptor(
    name='SearchBadpandas',
    full_name='blueintel.badapi.badpanda.BadpandaService.SearchBadpandas',
    index=0,
    containing_service=None,
    input_type=_BADPANDASEARCHREQUEST,
    output_type=_BADPANDASEARCHRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='SearchByDomain',
    full_name='blueintel.badapi.badpanda.BadpandaService.SearchByDomain',
    index=1,
    containing_service=None,
    input_type=_SEARCHBYDOMAINREQUEST,
    output_type=_BADPANDASEARCHRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='SearchByIP',
    full_name='blueintel.badapi.badpanda.BadpandaService.SearchByIP',
    index=2,
    containing_service=None,
    input_type=_SEARCHBYIPREQUEST,
    output_type=_BADPANDASEARCHRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_BADPANDASERVICE)

DESCRIPTOR.services_by_name['BadpandaService'] = _BADPANDASERVICE

# @@protoc_insertion_point(module_scope)
