# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: github.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cgithub.proto\x12\x17\x62lueintel.badapi.github\"M\n\x04\x46ile\x12\x0c\n\x04\x66ile\x18\x01 \x01(\t\x12\x13\n\x0b\x66ileVersion\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\t\x12\x0f\n\x07matches\x18\x04 \x03(\t\"y\n\x05\x41lert\x12\n\n\x02ID\x18\x01 \x01(\t\x12\x0f\n\x07RepoURL\x18\x03 \x01(\t\x12\x10\n\x08Keywords\x18\x05 \x03(\t\x12\x11\n\tTimestamp\x18\x06 \x01(\t\x12.\n\x07Matches\x18\x07 \x03(\x0b\x32\x1d.blueintel.badapi.github.File\"T\n\x11ListAlertsRequest\x12\x0b\n\x03org\x18\x01 \x01(\t\x12\x0e\n\x06viewed\x18\x02 \x01(\x08\x12\x11\n\tstartdate\x18\x03 \x01(\t\x12\x0f\n\x07\x65nddate\x18\x04 \x01(\t2m\n\rGithubService\x12\\\n\nListAlerts\x12*.blueintel.badapi.github.ListAlertsRequest\x1a\x1e.blueintel.badapi.github.Alert\"\x00\x30\x01\x42\x0cZ\n.;githubpbb\x06proto3')



_FILE = DESCRIPTOR.message_types_by_name['File']
_ALERT = DESCRIPTOR.message_types_by_name['Alert']
_LISTALERTSREQUEST = DESCRIPTOR.message_types_by_name['ListAlertsRequest']
File = _reflection.GeneratedProtocolMessageType('File', (_message.Message,), {
  'DESCRIPTOR' : _FILE,
  '__module__' : 'github_pb2'
  # @@protoc_insertion_point(class_scope:blueintel.badapi.github.File)
  })
_sym_db.RegisterMessage(File)

Alert = _reflection.GeneratedProtocolMessageType('Alert', (_message.Message,), {
  'DESCRIPTOR' : _ALERT,
  '__module__' : 'github_pb2'
  # @@protoc_insertion_point(class_scope:blueintel.badapi.github.Alert)
  })
_sym_db.RegisterMessage(Alert)

ListAlertsRequest = _reflection.GeneratedProtocolMessageType('ListAlertsRequest', (_message.Message,), {
  'DESCRIPTOR' : _LISTALERTSREQUEST,
  '__module__' : 'github_pb2'
  # @@protoc_insertion_point(class_scope:blueintel.badapi.github.ListAlertsRequest)
  })
_sym_db.RegisterMessage(ListAlertsRequest)

_GITHUBSERVICE = DESCRIPTOR.services_by_name['GithubService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\n.;githubpb'
  _FILE._serialized_start=41
  _FILE._serialized_end=118
  _ALERT._serialized_start=120
  _ALERT._serialized_end=241
  _LISTALERTSREQUEST._serialized_start=243
  _LISTALERTSREQUEST._serialized_end=327
  _GITHUBSERVICE._serialized_start=329
  _GITHUBSERVICE._serialized_end=438
# @@protoc_insertion_point(module_scope)
