# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import github_pb2 as github__pb2


class GithubServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.ListAlerts = channel.unary_stream(
        '/blueintel.badapi.github.GithubService/ListAlerts',
        request_serializer=github__pb2.ListAlertsRequest.SerializeToString,
        response_deserializer=github__pb2.Alert.FromString,
        )


class GithubServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def ListAlerts(self, request, context):
    """rpc ListRepos(ListReposRequest) returns (stream ListReposResponse) {};
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_GithubServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'ListAlerts': grpc.unary_stream_rpc_method_handler(
          servicer.ListAlerts,
          request_deserializer=github__pb2.ListAlertsRequest.FromString,
          response_serializer=github__pb2.Alert.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'blueintel.badapi.github.GithubService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
